version: "3.3"
services:
  Jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports: 
      - "8080:8080"
      - "8082:8082"
      - "8000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /opt/downloads:/var/downloads
      - /opt/jenkins_home:/var/jenkins_home
  Tomcat:
    image: tomcat:latest
    container_name: tomcat
    ports:
      - "8888:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  Mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: H@ckath0n
  Sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  Nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
